/**
 * Token type enum (short codes for smaller minified bundle). Tokenizer and parser use these.
 */
const Tok = Object.freeze({
  EOF: 'E',
  NUMBER: 'Nu',
  STRING: 'Sr',
  DOCSTRING: 'Ds',
  ID: 'Id',
  INDENT: 'Ii',
  DEDENT: 'Dd',
  NEWLINE: 'Nl',
  LPAREN: 'Lp',
  RPAREN: 'Rp',
  LBRACK: 'Lb',
  RBRACK: 'Rb',
  COLON: 'Co',
  COMMA: 'Cm',
  DOT: 'Dt',
  HAT: 'Ht',
  STAR: 'St',
  STARSTAR: 'S2',
  ASSIGN: 'As',
  EQ: 'Eq',
  NE: 'Ne',
  NOT: 'Nt',
  LT: 'Lt',
  LE: 'Le',
  GT: 'Gt',
  GE: 'Ge',
  PLUS: 'Pl',
  PLUSASSIGN: 'Pa',
  MINUS: 'Mn',
  RARROW: 'Ra',
  PERCENT: 'Pc',
  SLASH: 'Sl',
  SLASHSLASH: 'Sc',
  // Keywords (tokenizer emits these by uppercasing; we use short codes)
  VAR: 'Vr',
  FN: 'Fn',
  DEF: 'Df',
  STRUCT: 'Su',
  IF: 'If',
  ELSE: 'El',
  WHILE: 'Wh',
  FOR: 'Fr',
  IN: 'In',
  RETURN: 'Re',
  AND: 'An',
  OR: 'Or',
  TRUE: 'Tr',
  FALSE: 'Fa',
  SELF: 'Sf',
  NONE: 'Nn',
  BOOL: 'Bl',
  INT: 'It',
  LIST: 'Ls',
  COPYABLE: 'Cp',
  MOVABLE: 'Mv',
  CONTINUE: 'Cn',
  PASS: 'Ps',
  MUT: 'Mu',
  OUT: 'Ou',
  INOUT: 'Io',
  DEINIT: 'Di',
  COMPTIME: 'Ct',
});

/** Token type -> operator string for Binary/Unary nodes (eq, ne, +, -, //, etc.). */
const OP_FROM_TYPE = Object.freeze({
  [Tok.EQ]: 'eq',
  [Tok.NE]: 'ne',
  [Tok.LT]: 'lt',
  [Tok.LE]: 'le',
  [Tok.GT]: 'gt',
  [Tok.GE]: 'ge',
  [Tok.PLUS]: '+',
  [Tok.MINUS]: '-',
  [Tok.STAR]: '*',
  [Tok.SLASHSLASH]: '//',
  [Tok.PERCENT]: '%',
  [Tok.AND]: 'and',
  [Tok.OR]: 'or',
  [Tok.NOT]: 'not',
});

const tokenTypes = { ...Tok, OP_FROM_TYPE };
module.exports = tokenTypes;
module.exports.OP_FROM_TYPE = OP_FROM_TYPE;